import type { CmsData, Project } from "./cms-types";

export const DEFAULT_PROJECTS: Project[] = [
    {
        id: "p1",
        type: "horizontal",
        size: "half",
        title: "Barcelona Night Run",
        subtitle: "Documental · Marca deportiva",
        client: "Marca deportiva",
        role: "Productor · Operador de cámara · Editor",
        tools: "Sony FX3, Sigma 18-35, DaVinci Resolve",
        description:
            "Documental nocturno sobre la cultura runner en Barcelona. Rodado en una sola noche con un equipo reducido y óptica fija, con un look anamórfico y sonido binaural en post.",
        credits:
            "Dirección y montaje: Pol Sánchez Baena · Sonido: Estudio Halcón Audio · Color: Pol Sánchez Baena",
        format: "21:9",
        duration: "04:12",
        year: 2026,
        cover: "/images/portfolio-irl.png",
        videoUrl: "",
        tag: "Documental",
        showOnHome: true,
        order: 1,
    },
    {
        id: "p2",
        type: "horizontal",
        size: "half",
        title: "Lume — Vertigo",
        subtitle: "Videoclip",
        client: "Lume Records",
        role: "Productor · Editor · Colorista",
        tools: "Sony FX3, Atomos Ninja, DaVinci Resolve, Premiere Pro",
        description:
            "Videoclip para el single Vertigo del artista Lume. Rodaje en dos noches en Madrid con un esquema de luz mínima y dos cámaras. Edición rítmica al tempo del tema y look cinematográfico en post.",
        credits:
            "Producción: Pol Sánchez Baena · Cámara A: Pol · Cámara B: Lluís Pou · Música: Lume",
        format: "16:9",
        duration: "03:48",
        year: 2026,
        cover: "/images/portfolio-music.png",
        videoUrl: "",
        tag: "Videoclip",
        showOnHome: true,
        order: 2,
    },
    {
        id: "p3",
        type: "horizontal",
        size: "eq",
        title: "Northbeat S/S",
        subtitle: "Comercial",
        client: "Northbeat",
        role: "Productor · Editor",
        tools: "Sony FX3, Drone DJI Mini 4 Pro, DaVinci Resolve",
        description:
            "Spot de 45 segundos para la campaña primavera/verano de Northbeat. Rodaje en localizaciones de Costa Brava con drone y cámara en hombro. Edición rápida y enérgica.",
        credits:
            "Producción: Pol Sánchez Baena · Estilismo: Casa Mar · Música: librería licenciada",
        format: "16:9",
        duration: "00:45",
        year: 2026,
        cover: "/images/portfolio-brand.png",
        videoUrl: "",
        tag: "Comercial",
        showOnHome: true,
        order: 3,
    },
    {
        id: "p4",
        type: "horizontal",
        size: "eq",
        title: "Studio Vlog — Ep. 04",
        subtitle: "YouTube",
        client: "Atlas Studio",
        role: "Editor · Motion",
        tools: "Premiere Pro, After Effects, DaVinci Resolve",
        description:
            "Cuarto episodio de la serie Studio Vlog. Edición pensada para retención: hook fuerte en los 5 primeros segundos, ritmo sostenido y motion graphics ligero para los conceptos clave.",
        credits:
            "Grabación: equipo de Atlas Studio · Edición y motion: Pol Sánchez Baena",
        format: "16:9",
        duration: "11:47",
        year: 2025,
        cover: "/images/portfolio-youtube.png",
        videoUrl: "",
        tag: "YouTube",
        showOnHome: true,
        order: 4,
    },
    {
        id: "p5",
        type: "horizontal",
        size: "eq",
        title: "Atlas — Behind the Build",
        subtitle: "YouTube · Mini-doc",
        client: "Atlas Studio",
        role: "Productor · Operador · Editor",
        tools: "Sony FX3, Sennheiser MKE 600, DaVinci Resolve",
        description:
            "Mini-documental de 18 minutos sobre el proceso de construir un estudio de grabación desde cero. Tres días de rodaje, entrevistas a cámara y b-roll del taller.",
        credits:
            "Dirección, cámara y edición: Pol Sánchez Baena · Sonido: equipo Atlas Studio",
        format: "16:9",
        duration: "18:00",
        year: 2025,
        cover: "/images/hero-showreel-cover.jpg",
        videoUrl: "",
        tag: "YouTube",
        showOnHome: true,
        order: 5,
    },
    {
        id: "p6",
        type: "horizontal",
        size: "half",
        title: "Madrid After Hours",
        subtitle: "Comercial",
        client: "Marca lifestyle",
        role: "Productor · Editor",
        tools: "Sony FX3, Sirui Anamorphic 35mm, DaVinci Resolve",
        description:
            "Pieza nocturna en las calles de Madrid. Rodada con óptica anamórfica para reforzar la atmósfera urbana, con cortes al ritmo de la banda sonora.",
        credits:
            "Producción: Pol Sánchez Baena · AC: Marina Vidal · Música: librería licenciada",
        format: "16:9",
        duration: "01:30",
        year: 2025,
        cover: "/images/portfolio-irl.png",
        videoUrl: "",
        tag: "Comercial",
        showOnHome: true,
        order: 6,
    },
    {
        id: "p7",
        type: "horizontal",
        size: "half",
        title: "Neon Pulse — Single",
        subtitle: "Videoclip",
        client: "Independiente",
        role: "Productor · Editor · Colorista",
        tools: "Sony FX3, luces LED RGB, DaVinci Resolve",
        description:
            "Videoclip de neón puro: rodaje íntegramente en interior con luces RGB y humo. Look de alto contraste, edición sincronizada al beat y grade saturado en post.",
        credits:
            "Producción y edición: Pol Sánchez Baena · Talento: artista independiente",
        format: "16:9",
        duration: "03:12",
        year: 2025,
        cover: "/images/portfolio-music.png",
        videoUrl: "",
        tag: "Videoclip",
        showOnHome: true,
        order: 7,
    },
    {
        id: "v1",
        type: "vertical",
        title: "Vertigo — cut 9:16",
        subtitle: "Lume · Mar 2026",
        cover: "/images/portfolio-music.png",
        videoUrl: "",
        platform: "Instagram Reels",
        views: "4.2M views",
        description:
            "Corte vertical 9:16 del videoclip Vertigo, adaptado para Reels con un hook fuerte en los 3 primeros segundos.",
        role: "Edición · Adaptación 9:16",
        tools: "Premiere Pro · DaVinci Resolve",
        year: 2026,
        showOnHome: true,
        order: 1,
    },
    {
        id: "v2",
        type: "vertical",
        title: "BCN Night Run",
        subtitle: "Marca deportiva · 2026",
        cover: "/images/portfolio-irl.png",
        videoUrl: "",
        platform: "TikTok",
        views: "1.1M views",
        description:
            "Pieza vertical para TikTok extraída del documental Barcelona Night Run. Edición rítmica y subtítulos grandes.",
        role: "Edición · Adaptación 9:16",
        tools: "Premiere Pro · DaVinci Resolve",
        year: 2026,
        showOnHome: true,
        order: 2,
    },
    {
        id: "v3",
        type: "vertical",
        title: "Northbeat — Hook A",
        subtitle: "Comercial · 2026",
        cover: "/images/portfolio-brand.png",
        videoUrl: "",
        platform: "Instagram Reels",
        views: "620k views",
        description:
            "Variante A del comercial Northbeat para Instagram Reels. Optimizada para CTR y retención.",
        role: "Edición · Adaptación 9:16",
        tools: "Premiere Pro · DaVinci Resolve",
        year: 2026,
        showOnHome: true,
        order: 3,
    },
    {
        id: "v4",
        type: "vertical",
        title: "Studio — Highlight",
        subtitle: "YouTube Shorts · 2025",
        cover: "/images/portfolio-youtube.png",
        videoUrl: "",
        platform: "YouTube Shorts",
        views: "2.0M views",
        description:
            "Highlight de un episodio del Studio Vlog en formato YouTube Shorts.",
        role: "Edición · Adaptación 9:16",
        tools: "Premiere Pro · DaVinci Resolve",
        year: 2025,
        showOnHome: true,
        order: 4,
    },
    {
        id: "v5",
        type: "vertical",
        title: "Madrid After Hours",
        subtitle: "Vertical cut · 2026",
        cover: "/images/portfolio-irl.png",
        videoUrl: "",
        platform: "TikTok",
        views: "830k views",
        description:
            "Versión vertical del comercial Madrid After Hours con un montaje más agresivo.",
        role: "Edición · Adaptación 9:16",
        tools: "Premiere Pro · DaVinci Resolve",
        year: 2026,
        showOnHome: true,
        order: 5,
    },
];

export const DEFAULT_IMAGES: Record<string, string> = {
    "hero.showreel": "/images/hero-showreel-cover.jpg",
    "about.portrait": "/images/hero-showreel-cover.jpg",
};

export function buildDefaults(): CmsData {
    return {
        images: { ...DEFAULT_IMAGES },
        projects: structuredClone(DEFAULT_PROJECTS),
    };
}
